### ISSUE TITLE
ActiveJob Integration on Rails 4.2 - Couldn't find User

### ISSUE THREAD

**Issue by Jack12816** [plataformatec/devise#3550]
Hello,

as mentioned on the readme the ActiveJob integration on Rails 4.2 is as easy as adding
```ruby
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end
```
to the `User` model.

The good things is: a confirmation mail for a new user gets enqueued to my Sidekiq queue. But it looks like the job will be kicked off before the actual user instance is persisted. So the Sidekiq job fails for the first time. On a later retry the job gets done. **How can I ensure the user entity is persisted before we send any mails?**

Backtrace:
```bash
sidekiq_1     | 2015-04-03T16:32:19.315Z 1 TID-oshefkll0 ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper JID-bb1b58a2b3543aca381d2068 INFO: start
sidekiq_1     | 2015-04-03T16:32:19.348Z 1 TID-oshefkll0 ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper JID-bb1b58a2b3543aca381d2068 INFO: fail: 0.033 sec
sidekiq_1     | 2015-04-03T16:32:19.349Z 1 TID-oshefkll0 WARN: {"retry"=>true, "queue"=>"mailers", "class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "args"=>[{"job_class"=>"ActionMailer::DeliveryJob", "job_id"=>"6a519d5a-d2f6-4b4f-9490-4aa06a6c451c", "queue_name"=>"mailers", "arguments"=>["UserMailer", "confirmation_instructions", "deliver_now", {"_aj_globalid"=>"gid://api/User/1"}, "4-c3GN3_g2iMMkgsKMnJ", {}]}], "jid"=>"bb1b58a2b3543aca381d2068", "enqueued_at"=>1428078739.304505, "error_message"=>"Error while trying to deserialize arguments: Couldn't find User with 'id'=1", "error_class"=>"ActiveJob::DeserializationError", "failed_at"=>1428078739.34841, "retry_count"=>0}
sidekiq_1     | 2015-04-03T16:32:19.349Z 1 TID-oshefkll0 WARN: Error while trying to deserialize arguments: Couldn't find User with 'id'=1
sidekiq_1     | 2015-04-03T16:32:19.349Z 1 TID-oshefkll0 WARN: /home/web/.gem/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/core.rb:154:in `find'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/globalid-0.3.3/lib/global_id/locator.rb:126:in `locate'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/globalid-0.3.3/lib/global_id/locator.rb:17:in `locate'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/arguments.rb:88:in `deserialize_global_id'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/arguments.rb:74:in `deserialize_argument'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/arguments.rb:38:in `block in deserialize'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/arguments.rb:38:in `map'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/arguments.rb:38:in `deserialize'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/core.rb:85:in `deserialize_arguments'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/core.rb:75:in `deserialize_arguments_if_needed'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/execution.rb:30:in `perform_now'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/execution.rb:21:in `execute'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:75:in `execute_job'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:127:in `call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/logging.rb:24:in `with_context'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `call'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:51:in `block in process'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:98:in `stats'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:50:in `process'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
sidekiq_1     | /home/web/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

Versions:
* rails: 4.2.0
* devise: 3.4.1
* warden: 1.2.3

**Comment by nashby** [comment]
@Jack12816 hi. I think this might help you https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L123

**Comment by Jack12816** [comment]
@nashby This is quite much code to accomplish the integration. And if this is the correct solution the readme section is quite misleading. Sure there is no easy way?

**Comment by josevalim** [comment]
That's the way to do it right now, unfortunately. Maybe we can provide better integration in the future or you can use devise_async directly.

**Comment by betesh** [comment]
Just to make sure I understand, because `send_devise_notification` happens within the transaction, this only affect a Queue Manager that spawns a new thread within the same application process.  It doesn't affect AJ Queue Managers that queue jobs by writing a DB record, such as DelayedJob, because the DJ worker won't be able to see the job until the transaction is committed.  Is that correct?

**Comment by dennym** [comment]
Have the same problem over here. Maybe its possible to use some different custom `send_devise_notification` similar to https://github.com/mhfs/devise-async/blob/master/lib/devise/async/model.rb#L27

Althought I still dont get why the job is done before the entry is in the database. Since `send_devise_notification` is run `after_commit` So there is no chance that the db entry is not there.

**Comment by jimmy2** [comment]
I'm having the same problem.

Did anyone manage to come up with a feasible solution?

**Comment by dennym** [comment]
go for my solution one post above yours. We used it for a while and the error disappeared. we just had to drop it again because it was interfering with our custom email params.

**Comment by betesh** [comment]
http://www.justinweiss.com/articles/a-couple-callback-gotchas-and-a-rails-5-fix/ is a more general description of the ActiveJob / Sidekiq race condition and how to fix them.  It's not specific to devise, nor to ActiveJob.  The short answer there is to use `after_commit` but even that won't work is 100% of cases, so they make some other recommendations as well.

**Comment by fbernier** [comment]
So I did what's written in the README yesterday about activejob mailers ( https://github.com/plataformatec/devise?files=1#activejob-integration ) and ended up with exceptions when I deployed to production because of the issue mentioned here. I really think this should either be changed or removed from the documentation.

I ended up finding this in the code: https://github.com/plataformatec/devise/blob/49cf804c62b259af24291ca14b58bd32a905fa9e/lib/devise/models/authenticatable.rb#L123-L164

and will give it a try today. It's similar to @dennym's solution but not exactly the same. If it works I will open a PR to link to this instead in the README.

**Comment by connorshea** [comment]
Is this still a problem? I'd like to use the ActiveJob integration if possible.

**Comment by bntzio** [comment]
Any up to date solutions guys?

**Comment by ulissesalmeida** [comment]
@bntzio We have this work in progress PR https://github.com/plataformatec/devise/pull/4064

But I think we need review others callbacks that can generate these race conditions problems.

**Comment by ulissesalmeida** [comment]
Fixed on `4.1.0`

**Comment by connorshea** [comment]
Awesome, thank you @ulissesalmeida.

**Comment by Siraris** [comment]
I'm still having this issue on Devise 4.2

I added an after_create callback that uses ActionMailer to queue an email to be sent, but I'm getting sporadic : 

`ActiveRecord::RecordNotFound: Couldn't find User with 'id'=9658
  from active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
  from active_record/relation/finder_methods.rb:444:in `find_one'
  from active_record/relation/finder_methods.rb:423:in `find_with_ids'
  from active_record/relation/finder_methods.rb:71:in `find'
  from active_record/querying.rb:3:in `find'
  from active_record/core.rb:131:in `find'
  from global_id/locator.rb:130:in `locate'
  from global_id/locator.rb:155:in `block in locate'
  from global_id/locator.rb:165:in `block in unscoped'
  from active_record/scoping/default.rb:33:in `block in unscoped'
  from active_record/relation.rb:302:in `scoping'
  from active_record/scoping/default.rb:33:in `unscoped'
  from global_id/locator.rb:165:in `unscoped'
  from global_id/locator.rb:155:in `locate'
  from global_id/locator.rb:17:in `locate'
  from active_job/arguments.rb:97:in `deserialize_global_id'
  from active_job/arguments.rb:83:in `deserialize_argument'
  from active_job/arguments.rb:40:in `block in deserialize'
  from active_job/arguments.rb:40:in `map'
  from active_job/arguments.rb:40:in `deserialize'
  from active_job/core.rb:90:in `deserialize_arguments'
  from active_job/core.rb:80:in `deserialize_arguments_if_needed'
  from active_job/execution.rb:30:in `perform_now'
  from active_job/execution.rb:21:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq/processor.rb:152:in `execute_job'
  from sidekiq/processor.rb:134:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from sidekiq/middleware/server/active_record.rb:6:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/logging.rb:11:in `block in call'
  from sidekiq/logging.rb:32:in `with_context'
  from sidekiq/middleware/server/logging.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `call'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:129:in `block in process'
  from sidekiq/processor.rb:168:in `stats'
  from sidekiq/processor.rb:128:in `process'
  from sidekiq/processor.rb:80:in `process_one'
  from sidekiq/processor.rb:68:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'`

When I check, the user is clearly there, and transactional emails seem to be sent sometimes, but then randomly these exceptions are being thrown.  Any ideas?

**Comment by panasyuk** [comment]
@Siraris  I believe you should use after_commit callback.
