### ISSUE TITLE
Rails 5 WARNING

### ISSUE THREAD

**Issue by Kota-Kun** [plataformatec/devise#4058]
➜  rails generate devise:install                                                                                 ruby-2.3.0 
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Volumes/Media/Projects/rails5/SkyEngine/config/application.rb:8)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Volumes/Media/Projects/rails5/SkyEngine/config/application.rb:8)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Volumes/Media/Projects/rails5/SkyEngine/config/application.rb:8)
Running via Spring preloader in process 58559
    conflict  config/initializers/devise.rb
Overwrite /Volumes/Media/Projects/rails5/SkyEngine/config/initializers/devise.rb? (enter "h" for help) [Ynaqdh] y
       force  config/initializers/devise.rb
   identical  config/locales/devise.en.yml

**Comment by Kota-Kun** [comment]
fixed))

**Comment by Xosmond** [comment]
How did you solve it? Im refereeing to master branch but i still getting this warning many times.
